---
- name: get bootstrapping script...
  get_url: >-
    url={{gitlab_ci_multi_runner_rpm_url}}
    dest=/tmp/gitlab_ci_multi.sh
    mode=0755
    owner=root
    group=root

- name: running bootstrap script
  command: /tmp/gitlab_ci_multi.sh

- name: install gitlab-ci-multi-runner
  package: name=gitlab-ci-multi-runner state=latest
